# advice: NO FINAL SLASH in the path_constants paths.

image: spqr:booster
volumes:
  - "<simbridge>/tools/booster_motion:/app/booster_motion"
  - "<simbridge>/.pixi/envs/default:/app/bridge"
  - "/tmp/circus_ipc:/tmp/circus_ipc"
