[supervisord]
nodaemon=true

[program:booster-motion]
directory=/app/booster_motion
command=/app/booster_motion/booster-motion -mode sim -config ./configs/config_isaac.lua      # DON'T CHANGE
autostart=true
autorestart=true
stdout_logfile=/var/log/booster-motion.log
stderr_logfile=/var/log/booster-motion.err

[program:simbridge]
directory=/app/bridge
command=/app/bridge/simbridge
autostart=true
autorestart=true
stdout_logfile=/var/log/simbridge.log
stderr_logfile=/var/log/simbridge.err
